### ISSUE TITLE
Make credentials constants

### ISSUE THREAD

**Issue by bobby-brennan** [bobby-brennan/kaltura-recipes#21]
service_url, partner_id, admin_secret, secret and user_id

Should only be set once, and included/required in other files

**Comment by jessp01** [comment]
Still seeing:
$userId = "lucybot@example.com";

under test/golden/php/

Should use constant.

**Comment by jessp01** [comment]
Created pull:
https://github.com/bobby-brennan/kaltura-recipes/pull/25

**Comment by bobby-brennan** [comment]
Fixed by https://github.com/bobby-brennan/kaltura-recipes/commit/7f9827428f57fbedc83eec224c1b46c8cab33ded
